# Generated by Django 4.1.5 on 2023-01-22 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_stock_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 16, 44, 4, 596275)),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(upload_to='images'),
        ),
    ]
