# Generated by Django 4.1.5 on 2023-01-22 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_date_alter_product_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(default='/thumb.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 17, 8, 13, 744974)),
        ),
    ]
