# Generated by Django 4.1.5 on 2023-01-26 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_purchase_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 14, 1, 25, 94042)),
        ),
    ]
